$BaseDir = "C:\Users\hp\.gemini\antigravity\scratch\ennovation-rcm"
$htmlFiles = Get-ChildItem -Path $BaseDir -Filter *.html

foreach ($file in $htmlFiles) {
    $content = Get-Content -Raw $file.FullName
    
    # 1. Remove the empty SVG placeholders from src attributes
    $content = $content -replace 'src="data:image/[^"]+"', ''
    $content = $content -replace "src='data:image/[^']+'", ''
    
    # 2. Promote WP-Rocket lazy load attributes to standard native attributes
    $content = $content -replace 'data-lazy-src="', 'src="'
    $content = $content -replace 'data-lazy-srcset="', 'srcset="'
    $content = $content -replace 'data-lazy-sizes="', 'sizes="'
    
    # 3. Promote Swiper carousel lazy load attributes
    $content = $content -replace 'data-src="', 'src="'
    $content = $content -replace 'data-srcset="', 'srcset="'
    
    # 4. Clean up <noscript> tags generated by WP-Rocket (optional but good for cleanliness)
    $content = $content -replace '<noscript><img[^>]+></noscript>', ''

    Set-Content -Path $file.FullName -Value $content -Encoding UTF8
}

Write-Host "Successfully de-lazy-loaded all images across all HTML files!"
